version: '3.8'

services:
  postgres:
    image: postgres
    container_name: connection_db
    environment:
      POSTGRES_DB: connection_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
